### ISSUE TITLE
Easier Install/Add support for wxPython 4.0

### ISSUE THREAD

**Issue by klonos** [facelessuser/Rummage#106]
It would get you a larger user base if you provided pre-built binaries or some sort of downloader/installer GUI that downloads dependencies and runs the build/install scripts via a GUI.

**Comment by facelessuser** [comment]
@klonos, while I do enjoy hearing that people find the project useful, pulling in more users isn't really a goal  for me.

I'll start by saying that in the beginning, I did package this tool with PyInstaller for Windows.  But I did not provide binaries for Linux and macOS as it is much tricker to provide universal binaries for those operating systems as you have to build against the current OS.  I understand that what you are suggesting is a way to automate this process.  The way to approach those would be to offer maybe something like a  like a deb for Ubuntu (and various other packages for various other distros) so it could be built against those specific distros.  And for Mac, maybe something through homebrew or something.  Maybe even for Windows you could do something through Chocolatey. That's a lot of work, and I just don't have the time to invest in learning all of these packaging conventions to pull this off.  And then I would have to regularly package up all these bundles for various package managers.  If it wasn't just me heading this project, maybe, but as it stands, it's just me.

In the world of Python, installing WxPhython, and then `pip install https://github.com/facelessuser/Rummage/archive/1.0.2.zip` isn't too bad.  I realize not everyone that shows interest in this has Python already installed and is savvy at installing the necessary packages.  If WxPython is ever made to be pip installable, this would be even easier as I could probably just host Rummage on PyPi for easy pip install. I think that is the plan moving forward for WxPython Phoenix which will not only be pip installable, but work on Python 3 as well. Unfortunately, Phoenix still hasn't been officially released (last I checked), and I'm afraid Phoenix will require serious rework on my part as previous attempts to get this working with Phoenix have been far from trivial; they changed a lot.

Rummage is actually a tool created out of my own selfish need for a graphical search and replace tool that I could run cross platform.  The fact that others are interested in it is really just an extra.  That isn't to say I don't appreciate bug reports and feature suggestions from the community, but since this is an open source project, I don't really gain anything by pulling in more users.

Anyways, I welcome people with backgrounds in this kind of thing who are interested in providing such downloader/installers, but I don't think in the immediate future I have plans to look into this personally.

**Comment by facelessuser** [comment]
It looks like WxPython 4.0 (Phoenix) is released on PyPi now.  Ugh.  That means I should probably go through the pain of getting this compliant. Once I can pull this off, I  can put this on PyPi and then people can just `pip install rummage`. Assuming that name isn't already taken...

**Comment by facelessuser** [comment]
Okay.  While I don't plan on releasing binaries due to the issues I described above, I am working towards a single command install.  With wxPython 4.0 installable via pip, I can put Rummage on PyPi so that it can be installed with only `pip install rummage` or upgraded via `pip install --upgrade rummage`.

I spent some yesterday and was able to the basics of Rummage working with wxPython 4.0.  This will allow Rummage to run on Python2.7 and Python3.4+.  So any modern Python build.

I think this will make things much, much easier to install.  The branch is here: https://github.com/facelessuser/Rummage/tree/Phoenix. But I would not consider it stable yet. I have some bugs still to work out.  I have to work through all the features and make sure things are working.  I imagine there will be some GUI quirks to work out as well, but hopefully within a couple of weeks it will be up and running.

**Comment by klonos** [comment]
>@klonos, while I do enjoy hearing that people find the project useful, pulling in more users isn't really a goal for me.

I understand that more users also means more overhead, but it also means more testers and more eyes on the code. It might also be that someone (or someone**s** 😄) will come onboard and help by taking over documentation for example, so you can focus on the fun stuff (coding). In the long run, it will make for a better product. I am myself part of an open source project and I understand all that is involved in maintaining one.

For example, I don't know python, but that doesn't mean that I cannot search in the codebase (using Rummage; thank you!) for strings that have to do with user-facing text in the UI. I then can file PRs and help you out with improving that bit of the app 😉 

>...And then I would have to regularly package up all these bundles for various package managers. If it wasn't just me heading this project, maybe, but as it stands, it's just me.

Again, perfectly understandable. Filing this issue was *not* a "DO THIS RIGHT NOW" thing. It was more a "I'm adding this to the todo list that would make this product better" thing. Please excuse me if I am being a pest. That is what I do:

I am guilty of [50% of the issues opened for Backdrop](https://github.com/backdrop/backdrop-issues/issues?utf8=✓&q=is%3Aissue%20author%3Aklonos%20) (653 in total)

...but also responsible of [25% of the open PRs filed](https://github.com/backdrop/backdrop-issues/issues?utf8=✓&q=is%3Aissue%20author%3Aklonos%20) 😄 ...just trying to make this world a better place, same as you. One ticket at a time, one PR at a time 😉 ❤️ 

> ...but since this is an open source project, I don't really gain anything by pulling in more users.

Yes you do. Have faith brother. You are doing good 👍 👼

**Comment by facelessuser** [comment]
> I understand that more users also means more overhead, but it also means more testers and more eyes on the code. It might also be that someone (or someones :smile:) will come onboard and help by taking over documentation for example, so you can focus on the fun stuff (coding). In the long run, it will make for a better product. I am myself part of an open source project and I understand all that is involved in maintaining one.

I do enjoy feedback, and I do take it seriously.  Things that are within reasonable reach, I usually implement as long as it doesn't go against my general vision for the project, or if the payoff isn't worth the effort.  When I get around to them is sometimes another story.  And keep in mind that though I don't have any plans to provide binaries containing all the dependencies, I'm not against it if a reasonable way to accomplish the goal come to light.  Due to the fact that wxPhython provides Windows and OSX wheels, that tells me I could probably get away with a binary with those, but because they only provide a tar ball for Linux, it means wxPython must be built against the distro making that one difficult.  Maybe in the future I could bundle binaries at least for Windows and OSX, but we'll have to see.  I don't have immediate plans for that.

> Again, perfectly understandable. Filing this issue was not a "DO THIS RIGHT NOW" thing. It was more a "I'm adding this to the todo list that would make this product better" thing.

I understand.  I wasn't taking it as a "right now" thing, but I did want to give some background on it.  After seeing that Phoenix was finally released, it has motivated me to pump out a new release with Python3 support and easier installing :slightly_smiling_face:.  I've been waiting for a day when I could drop Python2 usage (not support, just personally on my machines), and the day has finally come.  GUI apps was the one thing I had to do on Python2.

I do appreciate the interest.  I'm quite fond of this project, so it is always nice to see I'm not the only one.  Hopefully with the new release, it will greatly alleviate install issues as I do understand it is annoying having to install the dependencies manually.  Hosting on PyPi will allow everyone to use pip, and since Rummage will now run on a lot more Python versions (up to even the latest), people won't be forced to install a very specific Python version.  They can use the latest and greatest and search away :wink:.

**Comment by klonos** [comment]
I wouldn't personally worry about a Windows port, since https://github.com/dnGrep/dnGrep does an amazing job! I'm personally a Windows user and looking for a dnGrep equivalent for Mac is what brought me to Rummage. Perhaps you can take a look at dnGrep and get some UI ideas 😉 ...if applicable in Mac of course.

Thank you for the time and energy you put in this project! I really appreciate it.

**Comment by facelessuser** [comment]
I'm a Window's user at work, and Mac/Linux at home.  I originally got this idea as I relied on grepWin, but couldn't find anything on Mac and Linux that scratched my GUI search itch.  It was heavily inspired by grepWin, but has diverged some.  Surprisingly, I mainly use Rummage on even my Windows system now.  I guess it keeps me in tune how well it's working on Windows.

I'll check out dnGrep and see what it can do.  I'm always open to new ideas.   As I'm actually not much of a UI guy (I do firmware for a living), I don't usually get too ambitious with my UI, but I am definitely open to new feature ideas.

**Comment by klonos** [comment]
> I do firmware for a living

Wow! You speak assembly then?

I did try grepWin at some point, but I ended up with dnGrep. I cannot remember the reason(s), but Their UI is very similar.

**Comment by facelessuser** [comment]
> Wow! You speak assembly then?

Yeah, a bit.  Modern firmware is mainly in C or C++, but yeah, you need to know the basics of assembly, but I rarely code in assembly, and when I do, it is very small snippets.

> I did try grepWin at some point, but I ended up with dnGrep. I cannot remember the reason(s), but Their UI is very similar.

Yeah, they look very similar. I didn't shop around too much once I found something that worked pretty good.

On a side note, wxPython 4.0 support has been merged with Python3 support.  I need to update documents a bit, setup PyPi auto-deployment and such, but it should be much easier to install on macOS and Windows when this drops on PyPi.  Linux is always Linux though. You have to apt-get (on Ubuntu) some prerequisites then  pip install, but that is something Linux users have come to expect anyways. I swear very little is without extra steps on Linux.  Oh well, maybe one day I can put together a deb for at least Ubuntu...maybe. 

I'm going to close this issue as I already have a "Get on PyPi" issue open which is the last step.

**Comment by facelessuser** [comment]
It's live.  You can pick up 2.0.1 on PyPi. A number of cross platform issues like tabbing problems etc. have also been fixed.
