### ISSUE TITLE
Import chain?

### ISSUE THREAD

**Issue by tmikaeld** [facelessuser/Rummage#129]
I need to do 113 different search and replace on a single file, but it seems i can only add them one-by-one in the chain editor, would it be possible to add a rule-import feature?

**Comment by facelessuser** [comment]
It's possible.  I can see that this may be useful.  I imagine an export and import feature may be nice.  

Not sure what format I would use for it yet.  JSON like the settings file is using?  YAML to allow easier regular expression entry?  A custom format?  That will likely need to be decided first, but I think the feature would be helpful.

Not sure when I will get to this, but I will put it on my list of things to do.

---

If you are in a bind right now, you can manually update the settings file (at your own risk), and pull this off:

Settings are found in the following locations (where `~` represents your user folder for your respective OS):

- Windows & OSX: `~/.Rummage/rummage.settings`
- Linux: `~/config/.Rummage/rummage.settings`

Find and replace rules are below.  Comments are just to explain and are not allowed in actual JSON format.

```js
"saved_searches": {
        "Copyright-update": [                                 // Unique key name
            "Copyright update",                                // Comments
            "(Copyright \\(c\\) \\d+ - 20)(\\d{2})",    // Find regex properly escaped
            "\\g<1>17",                                               // Replace regex. For replace plugins, this is the absolute path to plugin file.
            "is",                                                           // Flags (see below to learn more about flags)
            true,                                                          // Is regex?  False is literal.
            false                                                          // Using a replace plugin?
        ]
}
```

Flags represent the actual regular expressions flags.  For instance to normally turn on case insensitivity in a regular expression, you would do something like `(?i)`, so an `i` flag will turn on case insensitivity globally. `MULTILINE` is always used so no need to specify it here.  There is one exception though; the `regex` module has a feature that allows you to use a format string as a replace template and I have given it the arbitrary flag `F` for now.

Chains are in the following setting:

```js
    "chains": {
        "chain-example": [   // Unique chain name
            "example-1",         // The unique find and replace key from above
            "example-2"          // More unique find and replace key 
        ]
    }
```

Remember it will need to be proper JSON format.  Last entries in an array or dictionary can't have a trailing comma, and you must escape your strings properly.  The settings file doesn't expect human hands to be editing it, so not sure what it will do if the settings file is corrupt. So again edit at your own risk.

**Comment by tmikaeld** [comment]
Wow, thanks for the quick repland hackable solution!

I found TexFinderX that did the thing that i was looking for, it uses this format for multiple rules and use simple textfiles:

original <tab> replacement
original <tab> replacement
original <tab> replacement

So maybe keep it as simple as that?

**Comment by facelessuser** [comment]
> So maybe keep it as simple as that?

Maybe.  As shown above, the rules are a little more complicated than just the patterns (at least the rules are), the chains themselves are pretty simple though.

I'm not sure from your description if you are asking for find replace rule import **and** chain import, or just the chain part. Though I think importing both may be helpful.

**Comment by tmikaeld** [comment]
I haven't checked in to the complex rules yet, thought i can see at a glance that it's very powerful - more so than just regular regexp and that's great!

The specific issue was finding a GUI tool that does multiple regex find replace on a single or more file set, Rummage was the best one i found so far.

I use JSON for basically anything so I'm all in for using that.

**Comment by facelessuser** [comment]
> I use JSON for basically anything so I'm all in for using that.

Cool, I'll think about it a bit.  When allowing user edited JSON, I usually relax the rules a bit and allow comments and trailing commas.  It eases the issues of: "why don't my settings work?"   Anyways, I'll give it some thought, and when I have some time to tackle this. I'll update the issue with what I settled on.

**Comment by tmikaeld** [comment]
Cool, I love what you have done with this App!

Have you thought about packaging it as a packaged App and put on the App store? 
The amount of Find and Replace for MacOS can counted on one hand.

I've been using a Python script batch search/replace and using a GUI makes it so much faster, I'm quite sure a lot of more Developers feel the same.

**Comment by facelessuser** [comment]
> Have you thought about packaging it as an App and put on the App store?
The amount of Find and Replace for MacOS can counted on one hand.

When I first started writing this, in the early stages, I would use pyinstaller to build this as an app for Mac and Windows (probably shouldn't have since I think wxPython license is incompatible with that with my current license).  On top of that, I have to pay apple 100 bucks every year to sign apps and such, I'm not even sure if I could properly sign them with pyinstaller...maybe with a different solution like py2app....not sure.

I guess if I did that, I could charge a small fee to recoup the cost associated with paying apple to sign apps and to cover Apple's cut, but I don't know.  I guess I just haven't considered it fully.  I mainly wrote this because Mac solutions for this were pretty bad, so I wrote it just to make myself happy.  Since then, people have been stumbling upon it and using it as well :slightly_smiling_face: .

I  guess I won't say never, it just wasn't ever what I had my sights set on.  If I distribute it as an app, wxPython license won't allow me to release under my current license, or it gets more complicated.  I'd have to look at that closer.  If I was going to go that route, I'd probably rewrite the GUI in something more native to OSX and maybe bundle the python search and replace stuff internally, or rewrite it using a compiled regex library.  I think putting it on the app store would take it in a different direction.

**Comment by facelessuser** [comment]
So the actual feature is going to include export and importing chains, search and replace patterns, and or general settings.  This way you can transfer like settings between machines.  You can select what category of setting you wish to output or import.

There will have to be a layer that prevents OS specific settings from getting imported when not on that platform.

Since patterns could be entered manually into a JSON file, there will need to be a check to prevent stuff like `\n`.  As we are rendering in a single line input box, we don't actually allow true newlines and other such Python string references (`\a\v\f\t\r\n\b`).  These literal characters need to be identified and translated before import.

In general, we need a validation layer for import, less so for export.

**Comment by facelessuser** [comment]
The work is pretty much done for this.  I'll need to document exporting/importing settings, so this will definitely be in the next release.

**Comment by facelessuser** [comment]
This is now on master.
