### ISSUE TITLE
Show results/matches while search is going on.

### ISSUE THREAD

**Issue by klonos** [facelessuser/Rummage#140]
Thank you for all you hard work on this project @facelessuser ...I honestly appreciate the time you are dedicating.

Coming from Windows and https://github.com/dnGrep/dnGrep, I am used to see results while the search keeps running. Results are populating the list as more are found.

With rummage though, if I switch to the "Files" tab (which by then way might make better sense to be called "Results"), there is nothing shown, even though the status bar reports matches found. If you are searching through a large number of files, this becomes annoying, as you have to wait until the lengthy search is over. One might want to start doing some work in the already found results as the search finds more.

Thank you beforehand for considering this, and I hope that there is a way to do this relatively easy, so that you don't spend too much time.

**Comment by facelessuser** [comment]
First, thanks for the suggestion.

Yes, I originally approached it where the lists were updated as the search was going. Python's threading isn't really true threading though.  If I have two threads, Python is going to swap back and forth, but not really run them in true parallel.  See info on Python's [GIL](https://wiki.python.org/moin/GlobalInterpreterLock).  I believe you can release the GIL for certain tasks that you push down into in C code (which I'm doubt I'd do).

Anyways, in the past I tried updating it along the way, and what you get is the UI locking up when you are getting lots of simultaneous results.  So then you don't actually see it getting updated.  And it kind of slows down the whole search process.  It seems to handle 1 specialized task at a time better with mild update feedback.  Maybe this just shows I haven't figured out how to do it proper yet.

With that all said, I'll keep this open as a possibilities.  It's been a long time since I approached this, and I've learned more since I started this project.  When I have some time, I may look into this again in the future.  I won't promise anything, but it's a possibility. This would be a pretty low priority task though as this isn't a deal breaker for me and Rummage.

**Comment by facelessuser** [comment]
While thinking about this, there are a couple of things I'll need to do:

1. We are purposely using a list view that doesn't try to display all entries right away.  It actually loads entries on demand, a kind of lazy load if I recall correctly. I need to see if I am updating the list behind the scene whether the rendering updates properly.  Maybe I'll switch from lazy load?  Don't know.

2. I may need to restrict some operations like sorting while it is populating if the structures get messed up while appending new entries. I just need to check if lazy load, vs non-lazy load handle these things better.

3. I also need to ensure that while it is updating the view, that the main thread is given enough time to refresh the view, and that we don't update it too often to bog down the searching with too many UI refreshes slowing it down too much.

I'm not concerned if the search time increases but is essentially the same.  What I mean is that I *think* search time is calculated, then we populate the view.  In the case of live updating, we'd be folding in the updates in between accounting for UI update time. But if it spends way more time updating the UI, we may have to rethink.  Basically we want a good balance of performance and updates.  And it needs to work well with Python's threading.  Hopefully this is all possible.

**Comment by facelessuser** [comment]
FYI, I've been looking into this with some promising results. I'm very optimistic that this will be in the next release. At the very least it may be under an experimental toggle in the settings menu, but hopefully, it will be enabled as a stable feature.

**Comment by facelessuser** [comment]
If we are going to be updating live, the progress bar may now be unneeded.  It was kind of something to let people focus on as we didn't have live results, but now that we might, we can just switch to the tab to show results while we show update info in the status bar.

**Comment by facelessuser** [comment]
Notes to self:

- [ ] Should put result click events and context menu actions under the thread wait lock so we don't try to access the results table behind the scene while it is getting updated during active search.
- [ ] Hover on result action should be disabled during active search as the current status of the search in the status bar is of far more importance.
- [ ] See if we can take out unnecessary actions when updating result table to ensure we are performing at peak speed during an update.

I will have to also test this on a really big project with a lot of matches to ensure reasonable performance, but so far in current stress tests, things are looking fine.  Search time increases some as we are actively timing search **and** UI refreshes, but this was expected.  Search itself should be relatively the same.  We just need to make sure we are doing the bare minimum during UI refresh.

**Comment by facelessuser** [comment]
Performance is looking really good.  This has turned out to be easier than I thought.  This is looking to be safe to push as a stable feature moving forward.  Sorting looks to be safe during search as well, though anything that comes in after the sort will not be sorted which will require sorting again.  As the status bar will be the reflecting current search progress, I dug in and fixed Windows status bar flicker as well.  Current dev branch is here: https://github.com/facelessuser/Rummage/tree/live-update.

**Comment by facelessuser** [comment]
Done

**Comment by klonos** [comment]
Thank you for implementing this great feature @facelessuser 👍 ...one small comment re UX would be to expose the/a stop button in the "Files" tab. I'll file a separate ticket for that though...

I have not checked the queue in a while, but going through the changelog was quite a pleasant surprise 6+ months later 😄 ...thanks once again.
