### ISSUE TITLE
KDE right-click menu

### ISSUE THREAD

**Issue by toxpal** [facelessuser/Rummage#248]
I don't know if this can really be considered as issue, but maybe someone will know the answer.

I would like to create service (right-click) menu to start Rummage in selected directory on antergos Linux (using KDE with Dolphin file manager). So after studying https://techbase.kde.org/Development/Tutorials/Creating_Konqueror_Service_Menus I created service menu:

```
[Desktop Entry]
Type=Service
ServiceTypes=KonqPopupMenu/Plugin
MimeType=inode/directory
Actions=openRummage

[Desktop Action openRummage]
Name=Open Rummage
Icon=edit-find-replace-symbolic
Exec=python -m rummage
```

The menu is visible in Dolphin, but once I click it, I only see “Open Rummage” entry in task manager for a second, and then it auto-closes. Running the same command python -m rummage via terminal works fine.

Rummage user guide says I should be able to run app using command **rummage** OR **python -m rummage**, but for some reason only **python -m rummage** works for me. Typing **rummage** returns error **bash: rummage: command not found**

Maybe that’s related somehow?

My service menu itself is OK, because if I replace python -m rummage with geany (or whatever app), it opens specified app without any problems.

P.S. Did the search and found an old topic where someone had success with creating right-click menu with Ubuntu's file manager, but it doesn't work on other platforms.

**Comment by facelessuser** [comment]
> Typing rummage returns error bash: rummage: command not found

Python script folder must be found in your path for this to work, maybe it isn't in the path via this method?  You can always give the full path which should work (I assume).  Assuming calling `rummage` from the command line works for you, you can get the full path via `which rummage`.

> python -m rummage

Maybe give `pythonw -m rummage` a try? `python -m rummage` will only stay alive as long as the terminal session doesn't close because it calls rummage as a console app, but `pythonw -m rummage` will call rummage as a window app essentially spawning it independently from the console as a background process. 

Hopefully one of those will work for you.

**Comment by toxpal** [comment]
Thanks, will try it tomorrow and update this post.

**Comment by toxpal** [comment]
>Python script folder must be found in your path for this to work, maybe it isn't in the path via this method? You can always give the full path which should work (I assume). Assuming calling rummage from the command line works for you, you can get the full path via which rummage.

Since I'm new into Linux world, I'm not very sure what do you mean exactly...

I guess that python is installed at **/usr/lib/python3.6/** on my system. At least I see tons of *.py files there. 

I also see **/home/MY_USERNAME/.local/bin/rummage** file, so if I type  **/home/MY_USERNAME/.local/bin/rummage** in command line, Rummage is launched (the same happens if I type **/home/MY_USERNAME/.local/bin/rummage3.6**)

Unfortunately, if I enter this command into my service menu, it "works" the same way - I only see “Open Rummage” entry in task manager for a second, and then it auto-closes.

**which rummage** returns:
>which: no rummage in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)

>Maybe give pythonw -m rummage a try?

If I use this command in service menu (_Exec=pythonw -m rummage_), I see a popup:
_Sorry - Dolphin
Could not find the program pythonw_

Entering pythonw -m rummage into terminal returns:
_bash: pythonw: command not found_

Thanks for all your help and efforts.

**Comment by facelessuser** [comment]
Hmm that is weird.  `pythonw` is supposed to be available along side `python`.  You'll have to give me some time to investigate this.  I'm using a Linux system with Gnome, not KDE, and I don't think I do the DesktopEntry approach...

I'll have to attempt this later.

**Comment by facelessuser** [comment]
I'm having some memory of running into this issue before the more I think about it.  That may have led me to how I do things now with Ubuntu Nautilus...

I think this is generally good to figure out as it will be helpful to a number of Linux users.

**Comment by toxpal** [comment]
Maybe you remember this one - https://github.com/facelessuser/Rummage/issues/38 ?

**Comment by facelessuser** [comment]
Yeah, that is probably it.  I just have to find the time to look into this.

**Comment by facelessuser** [comment]
This worked for me in Ubuntu with KDE and dolphin:

Created a file under `~/.local/share/kservices5/ServiceMenus/rummage.desktoop`:

(your path to resources may vary)

```
[Desktop Entry]
Type=Service
Icon=/usr/local/lib/python3.5/dist-packages/rummage/lib/gui/data/rummage_hires.png
X-KDE-ServiceTypes=KonqPopupMenu/Plugin
MimeType=all/all;
Actions=rummage;
Encoding=UTF-8

[Desktop Action rummage]
Name=Rummage Here
Icon=/usr/local/lib/python3.5/dist-packages/rummage/lib/gui/data/rummage_hires.png
Exec=rummage --path "%f"
```

I found the path for configs by running (I had to create the directory though):

```
facelessuser@facelessuser:~$ kf5-config --path services
/home/facelessuser/.local/share/kservices5/:/usr/share/kservices5/
```

Once I created my `.desktop` file, I ran this (not sure if I needed to, but I read somewhere to do it, maybe it isn't actually necessary):

```
facelessuser@facelessuser:~$ kbuildsycoca5
```

Then I closed all open Dolphin windows and reopened Dolphin:

![screenshot_20180711_132251](https://user-images.githubusercontent.com/1055125/42595175-a82345f8-850e-11e8-990d-65af6c95b57e.png)

Worked fine and opened Rummage without any issues.

I also tried with `python3.5 -m rummage` and that seemed to work as well:

```
[Desktop Entry]
Type=Service
Icon=/usr/local/lib/python3.5/dist-packages/rummage/lib/gui/data/rummage_hires.png
X-KDE-ServiceTypes=KonqPopupMenu/Plugin
MimeType=all/all;
Actions=rummage;
Encoding=UTF-8

[Desktop Action rummage]
Name=Rummage Here
Icon=/usr/local/lib/python3.5/dist-packages/rummage/lib/gui/data/rummage_hires.png
Exec=python3.5 -m rummage --path "%f"
```

I'm assuming this would work on other distros with KDE and dolphin.

FYI, it seems Linux does not have a `pythonw`.  Didn't realize this, so that is why you coudln't find it.  I know it exists on Windows, not sure about macOS, I'll have to check just for curiosity.

**Comment by toxpal** [comment]
**Thank you, it worked** on antergos KDE too!

It looks that the most important aspect here was **kbuildsycoca5** command. Right after I executed it, my old service menu also started working.

P.S. Here's a slightly simplified version of KDE service menu for Dolphin in case someone needs it:

```
[Desktop Entry]
Type=Service
ServiceTypes=KonqPopupMenu/Plugin
MimeType=inode/directory
Actions=openRummage

[Desktop Action openRummage]
Name=Open Rummage
Icon=edit-find-replace-symbolic
Exec=python -m rummage --path "%f"
```

As you see, I removed duplicated icon path and used plain **python** command instead of **pythonVERSION_NUMBER**, so the same menu works with all versions of python, making it future-proof.

Once again, thanks for all your help; you are one of the most responsive developers I ever saw.

**Comment by facelessuser** [comment]
> As you see, I removed duplicated icon path and used plain python command instead of pythonVERSION_NUMBER, so the same menu works with all versions of python, making it future-proof.

I have multiple Python versions installed, so calling python gives me python 2, which I don't want.  I could just call `python3`, but I was just emphasizing to specify the Python that has the rummage you want in case you have multiple Python 3 versions on your system (which I often do).

> Once again, thanks for all your help; you are one of the most responsive developers I ever saw.

It helps that I use Rummage daily in my workflow.  It gives me incentive to jump on features I find interesting and useful.

Anyways, glad you got it all working.
