### ISSUE TITLE
Can't install on Python 3.7

### ISSUE THREAD

**Issue by toxpal** [facelessuser/Rummage#270]
Firstly, I don't know if it's a problem of Rummage or Python, so feel free to close/delete this issue in case it has nothing to do with Rummage.

Recently, my system (antergos, which is Arch-Linux based) was upgraded and python 3.6 was replaced with 3.7. Since then, Rummage doesn't work anymore. **python -m rummage** returns - **No module named rummage**

Unfortunately, I can't even install it again. pip install starts fine, it downloads Rummage, and a few minutes later it contains hundreds of lines with errors. Here's the full log:

https://pastebin.com/KVuiRnLh

If I try to install it via Python 2.7 by running **/usr/bin/python2.7 pip install --user rummage**, this error comes:

```
Traceback (most recent call last):
  File "pip", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==18.0' distribution was not found and is required by the application

```

Once again, please accept sincere apologies if it's not Rummage problem, I just don't know what else to do because I use Rummage daily and now my system is useless. 

I found dozens of same problems on Arch Linux forums, where users had broken apps after Python was upgraded to 3.7, but almost all of them were solved by re-building these applications via AUR. Unfortunately, Rummage is not available in AUR, so I have no idea what else to do...

**Comment by facelessuser** [comment]
What version of pip and setuptools so you have? Or maybe better, make sure you have the latest. I've generally seen issues since the big overhaul of pypi recently if you are in a old version.

Make sure to uninstall rummage before attempting to install rummage again.

**Comment by toxpal** [comment]
pip was the latest (18.0) and setuptools was 39.2, so upgraded to 40.0.

Still the same error. Except that error is now displayed only when using python 3.7, python 2.x stopped working at all:

```
$ /usr/bin/python2.7 pip install --user rummage
/usr/bin/python2.7: can't open file 'pip': [Errno 2] No such file or directory
```

**Comment by facelessuser** [comment]
> python 2.x stopped working at all:

This just looks like it didn't install properly as now it can't find `pip`.

Linux often does this weird thing where they have their own packages for `pip`.  For instance on Ubuntu, you can install it via a nonstandard way `sudo apt-get install pip-python` (something like that). It varies from distro to distro, but you can't really just upgrade with `sudo pip install -U pip` because the distro installs it in an unexpected way, so it often breaks things instead.

I had trouble with the Ubuntu default pip package, so I upgraded via `curl https://bootstrap.pypa.io/get-pip.py | sudo python`.  I don't recall if I had to do additional steps (uninstalling the default pip or not - I just don't remember), but I know, ultimately, the final step was using the curl command posted above.

The Python2 error you originally posted is clearly a pip error, not a rummage specific error: `pkg_resources.DistributionNotFound: The 'pip==18.0' distribution was not found and is required by the application`.  If you can successfully install the latest pip properly, it *should* install, but it looks like there is an additional issue which is highlighted in your Python 3.7 issue.

---

Let's get back to Python 3.7. I don't have Python 3.7 on my Linux distro...I think it is 3.5, but I've installed it on 3.7 on my Mac with no issues.  Looking at the pastebin error, I see:

```
   ../../../../sip/cpp/sip_advwxPseudoDC.cpp:2836:2: fatal error: error writing to /tmp/ccEwE8V4.s: No space left on device
    };
     ^
   compilation terminated.
```

This is a wxPython build error.  This has absolutely nothing to do directly with Rummage either, but Rummage needs wxpython to work.  It appears it runs out of space on the device while building.  Do you build this with sudo without sudo?  Is there something additional you need to do to allow this build?  Please check some forums dealing with similar errors on Arch Linux.  Maybe there is a cache you need to clear?  Expand some temp space?  I'm not sure.  You can try posting this error on the wxPython issue site, maybe they have some suggestions.

90% of the time when Rummage fails to install, it is because wxPython fails to install, and most of the time it is on Linux as Linux has no wheels for wxPython, and has to build it. In short, most Rummage install issues are actually wxpython install issues. In general, you should focus on **just** getting wxPython to install first, after that, everything else should install smoothly.

**Comment by facelessuser** [comment]
Maybe this link will help? https://stackoverflow.com/questions/40755610/ioerror-errno-28-no-space-left-on-device-while-installing-tensorflow/40755688

**Comment by toxpal** [comment]
Thanks, I'll try to dig into wxpython error deeper... As for "no space left" error, disk has plenty of free space. I found (on forums) that this error can actually be caused by different things, so I'll just probably start debugging.

Anyhow, thanks for your assistance. I was assuming it's not Rummage's fault, just wanted to be sure. Thanks once again.

**Comment by toxpal** [comment]
I did find and fixed the issue (thanks to your help)!

The issue was related to wxpython. For some reason, it couldn't be installed via pip (as you see in the errors). So I opened Package Manager and searched for wxpython. Sure enough, it wasn't installed. I tried to install it, and got a bunch of errors about existing directories in /usr/bin. So I removed those directories, and wxpython was installed fine.

Then, installing Rummage took about 5 seconds via pip, and everything works great again.

**Comment by facelessuser** [comment]
I suspect it is most likely possible to build.  I imagine maybe changing where the build occurs may help.  I've seen issues like this before (even though I had plenty of hard drive space and memory).  I think the temp directory is allocated differently.

With that said, using the prepackaged wxPython is fine if it moves you forward. Quicker to install probably as well.  The problem is if there is a reason for Rummage to require a later version, you will be limited to what is provided by your distro, but hopefully that won't be needed any time soon.
