### ISSUE TITLE
Add Rummage to Arch package repository

### ISSUE THREAD

**Issue by toxpal** [facelessuser/Rummage#301]
Not really an issue, but a suggestion.

Did you consider adding Rummage to the official Arch package repository (or Arch user package repository)? This OS (and many variations of it, such as Manjaro, antergos) is extremely popular, and it has  no single tool which is as good and powerful as Rummage. In fact, there are very few GUI grep tools, and they are out-of-date or crappy.

Hence, having Rummage in Arch package repository would enable anyone to find/install/update Rummage automatically, with a single click. I don't know how much efforts it needs, but according to some tutorials, it's enough to run PKGBUILD ( https://fusion809.github.io/how-to-create-archlinux-repository/ ). 

Once again, thank you for greatest grep GUI for Linux.

**Comment by facelessuser** [comment]
@toxpal, I'm not against the idea, but I would not want to maintain it myself as I don't use Arch Linux regularly. The maintenance cost of packaging for different distros and operating systems is really something I just don't currently have time for.  But if anyone wanted to take up the task of providing automated packages for their favorite OS, I would have no problem with that.

With all of that said, I generally recommend people to use `pip` though as you can thing get the latest Rummage at any time.

The hardest part of installing Rummage is honestly installing wxPython.  It is the only *required* package that is not pure Python.  Luckily on macOS and Windows, there are wheels, but it has come to my attention that *most* Linux distros usually have a wxPython package that satisfies Rummage's requirements, so that can usually be used instead of hunting around for wxPython dependencies and trying to pip install wxPython.  Now that wxPython Phoenix has a stable release, I don't imagine bumping the required version for that package very often unless there was a strong *need*. After that, Rummage is just a pure Python package requiring `pip install Rummage`. Any *extra* packages like cchardet or regex are not required (though I use them).

> Once again, thank you for greatest grep GUI for Linux.

Thank you, it is always nice to see people finding use for tools like this. I honestly thought I was going to be the only one using Rummage when I wrote it. You never know whether people will stumble on it and like it 🙂 .
