### ISSUE TITLE
Window position and size not saved on KDE

### ISSUE THREAD

**Issue by toxpal** [facelessuser/Rummage#329]
I have this issue since the first day when started using Rummage (about a year ago), and it's still present in 4.6.0.

When I work with Rummage, I resize its window (make it bigger) and move it to a different position. Unfortunately, window size and position is reset every time I close the app. I don't know if it's app or OS problem (I believe OS should remember size/position of each app), but other apps don't lose their sizes/positions after closing, so I guess this behavior is related to Rummage.

Not a big deal, but if there's any chance to fix it, that would be great.

**Comment by facelessuser** [comment]
Currently, I'd say this is not an "issue" per se. This is behaving as intended, though it may not be desirable for some. This is what is happening:

1. At some point a user wanted internationalization. So I added that, but string size for label can change with internationalization, so we best fit everything for the minimum size. This keeps us from having scroll bars in the main dialog interface.

2. I'm not sure the OS remembers the position of the app normally. Keep in mind, Python is the main application, not Rummage. Rummage is running inside Python. I imagine KDE or whatever OS would mainly see a window from Python, not specifically Rummage, but maybe I'm wrong. Currently we do invoke a centering of the window on load.

GTK is particularly annoying (through wxPython) with window sizing. If I don't size things out of the box, I get some weird sizing. With GTK, I have to go one step further and make sure resizing occurs after initialization with a callback, while on every other OS I can size in intialization.

I'm opening to experimenting in the future to see if the OS will remember sizes. I would maybe have to just set minimum sizes. I'm not entirely sure how well this would work.

It is possible I could manage it myself, but I'd have to cache number of desktops, sizes of desktops, what internationalization strings I'm using and have they changed, position of dialog(s) (though most likely I would only waste time on the last instance). A lot of little tedious things. It isn't impossible, it just may be more work than I really care about.

The current behavior was the easiest sane path, which is why that is what we currently have.

**Comment by toxpal** [comment]
> so we best fit everything for the minimum size

It explains everything and really makes sense. Thank you.

**Comment by facelessuser** [comment]
It may still be possible to get what you want. I figure maybe when we close, we just cache the window size and position and display the dialog is on and its position.

If when we start up a new window and it is and the number of displays and display sizes are the same, we can try to size and position the window as it last was, assuming that the size is not less than the calculated minimum.

It's possible. Definitely low priority. I may look into it in the future.

**Comment by toxpal** [comment]
Actually, I got it solved now using KDE's Kwin. In case someone has the same issue in future, here's a basic tutorial how to force window sizes using KWin - https://www.maketecheasier.com/set-special-window-settings-with-kwin/ (I used "Force" option because "Apply initially" didn't work with Rummage for some reason).

**Comment by facelessuser** [comment]
If that works for you, great. It's not really cross platform, but I've also never heard this request until now, so I probably won't work about it for now. It may be something I tinker with in the future though.

**Comment by facelessuser** [comment]
The initial sizing probably didn't work for you because of the reasons I outlined above. In Linux, I have to resize in a callback after initial reload or the sizes don't quite work. This is only done on Linux. Every other platform seems to not need this :man_shrugging: .
