### ISSUE TITLE
This program needs access to the screen (continued: python 3.x / rummage 4.x)

### ISSUE THREAD

**Issue by klonos** [facelessuser/Rummage#346]
Filing this as a follow-up to #127, which seems to be valid during a pre-python3 and pre-rummage4.x era.

@facelessuser I have added comments in #127 with detailed steps of what I've gone through to get to a point where rummage 4.x is installed, but refuses to run, throwing the "This program needs access to the screen" error.

Now, since #127 has been closed, perhaps you may not want to reopen it, but I thought it'd be best to keep things in a single place, so that people have some context of what was previously attempted by others. Please let me know if you'd prefer to keep that issue closed, and to start a new thread here; or if you'd rather we close this issue and keep things in #127 instead.

**Comment by facelessuser** [comment]
I need some info on why you need to use brew instead of the official Python installer. Is there a specific reason?

I saw you mention you attempted the official installer but had issues, but I have received no additional information there. Ideally, I'd like to help you resolve the issue there if possible as I know that works. Investigating a solution for brew make take more time.

**Comment by facelessuser** [comment]
I think this also probably explains color issues with dark mode that you had on mac as well. In the original issue that I linked linked in wxPython, that user was using brew as well. I did not use brew in my tests, so I never reproduced the issue. I would strongly advise using the official installer unless there is a good reason to use brew.

Upgrading isn't bad with the official installer only requires you to download the next minor point release (3.7.X) and install it on top. Major release upgrades (3.X.X), are easy as well with downloading the installer. If you want to remove the older major release (don't remove mac's official Python), it can be mildly trickier using the official installer, but it isn't overly complicated, and there are guides: https://macflypro.com/uninstall-guides/remove-python.html.

Anyways, it seems that brew may be more trouble than it is worth in regards to Python 3 with wxPython. With that said, if possible, I'll see what steps need to be taken to get brew to work with wxPython, but it is lower priority.

**Comment by facelessuser** [comment]
An aside, wxPython in a virtual environment (`pyenv`) is known to have issues.  I imagine that using brew normally should work, but I haven't tested that yet.

Considering that I do most of my development on macs, I believe we could work through this as I have not had any issues using Rummage on macs. It is only when people are trying to do things like run it in a virtual environment that I've seen people have issues. Normal `brew` I'll have to test locally, but the official installer works with no issues, and if your having issues, I can probably talk you through your issues.

**Comment by facelessuser** [comment]
Okay, I installed Python 3.7.3 via brew on my mac. I then installed wxpython and lastly rummage. I then ran rummage without any issue. You will notice in my instructions below that I reference the full path of my brew python binary. This is because it was not symlinked because I have the official install already symlinked. Anyways, here it goes:

- `brew install python3`
- `/usr/local/Cellar/python/3.7.3/bin/python3.7 -m pip install wxpython`
- `/usr/local/Cellar/python/3.7.3/bin/python3.7 -m pip install rummage`
- `/usr/local/Cellar/python/3.7.3/bin/python3.7 -m rummage`

And then it ran just fine. So it runs good with brew, just not in a virtual environment.  I did not use `brew install wxpython`. This is unnecessary on a mac. You can use pip directly as wxPython provides wheels for mac (already compiled versions).

**Comment by facelessuser** [comment]
If you have a specific issue that is not related to virtual environments, please let me know so we can work through it.

**Comment by klonos** [comment]
Thanks for taking the time to respond @facelessuser 🙏

> ...the official installer works with no issues, and if you are having issues, I can probably talk you through your issues.

I may actually have to take that offer. Here's a bit of a background:

- I initially started using rummage 3.x a few years back. I had that installed via `brew` (**not using `pyenv` at all**), with python 2.x.
- When rummage 4.x got released, I had to somehow get my system updated to use python 3.x, as this was a requirement (I don't use python for anything else - I don't code in it).
- All my efforts to make python3 become the default in my Mac failed (I had to use `python3` in the command line), **so `pip install rummage` would always result installing rummage3** instead of 4.x. So up till a week or so ago, I was using rummage3 (and let me stress this once again: without `pyenv`).
- I decided to give installing rummage 4.x another go, and seeing your numerous previous suggestions to use the official version of python, I decided to fully remove all traces of brew-installed python from my Mac. I think that I achieved that, but I may have missed something; I consider myself pretty tech-savvy, but not an expert in this (making a living as a Windows and linux Computer/Network Engineer capacity for decades - **Mac user only for about 2-3years**).
- Starting afresh, I installed python using the official installer: https://www.python.org/ftp/python/3.7.3/python-3.7.3-macosx10.6.pkg ...this once again resulted in this:

```
$ python -V
Python 2.7.16

$ python3 -V
Python 3.7.3
```

This would not be a problem for me, but I was back in the situation where `pip install rummage` installs rummage 3.x instead of 4.x.

- So only then I removed the official install of python, and tried `brew` + `pyenv`, in order to have python3 be the default. This has worked, and `pip install rummage` installs rummage4 without any problems 👍 🎉 ...but I obviously rushed to celebrate, as trying to use rummage now results in the "This program needs access to the screen" error.

And this brings us to where we are now. I hope that the above answers this comment of yours:

> It is only when people are trying to do things like run it in a virtual environment that I've seen people have issues.

...basically, **I couldn't install rummage 4.x at all before I tried `pyenv`**.

**Comment by facelessuser** [comment]
> All my efforts to make python3 become the default in my Mac failed (I had to use python3 in the command line), so pip install rummage would always result installing rummage3 instead of 4.x. So up till a week or so ago, I was using rummage3 (and let me stress this once again: without pyenv).

This is your whole problem. Use `pip3` or `pip3.7` or `python3 -m pip`.  I personally just call `python3.7 -m pip`. I have numerous versions installed, so I usually just specify the full version I am working in.

Python uses the mechanism of creating symlinks in the form `pythonX.X` for different versions so they can exist side by side. I have 2.7, 3.6, 3.7, and will have 3.8 beta probably very soon. Additionally, the latest Python you have also gets installed with `pythonX`, so if `3.7` is your latest, usually `python3` will be 3.7.

Pip follows this convention as well, and is usually bound to `pipX.X` and I think `pipX` potentially as well. I usually just use the full version though 🤷‍♂ .

You man not realize it, but while Rummage can be called from command line via `rummage`, you can also call it via `rummage3.7` if it is installed under Python3.7.  I do this so you can make sure you are calling the one you think are.

Hopefully this explanation makes things much easier for you to understand. You probably had a workable environment all along but didn't realize it.

**Comment by klonos** [comment]
> You probably had a workable environment all along but didn't realize it.

You are absolutely right. Problem sorted! 👍

The documentation in https://facelessuser.github.io/Rummage/installation could use some updating, and perhaps I can help with it, as a way to contribute back. So the current documentation refers to a method to get Rummage installed with python 2.x, which always results in Rummage 3.x being installed. Perhaps it may be worth keeping it in place for people running older versions of Mac OS, so here's the steps to get Rummage 4.x installed, with python 3.x:

For non-python-savvy people that come to this issue in the future (assuming you have `brew` and `pip` + `pip3` installed already):

1. Install the latest official package for Mac from https://www.python.org/downloads/mac-osx
2. Make sure python 3 works by running `python3 -V` on your terminal. You should see something like `Python 3.7.3`.
3. Make sure you have pip3, by running `pip3 -V`. You should see something like: `pip 19.1.1 from /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip (python 3.7)`.
4. Install rummage 4 by running `pip3 install rummage`
5. Finally run rummage: `python3 -m rummage`

You will see this error in your terminal while the Rummage window is open:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rummage/lib/gui/notify/notify_osx.py", line 167, in setup
    assert(term_notify is not None and exists(term_notify))
AssertionError
```

...it is safe to ignore, and it will go away once you quit the Rummage window.

**Comment by klonos** [comment]
...this issue can be closed. It is unfortunate that the current documentation around installing rummage is making assumptions around people knowing their way around python, when all they need is to get Rummage installed 😅 ...I am assuming that if others came to this project and had the same issue, they have simply given up.

Thank you heaps for all the time and energy you have put into this project, for making it feely available for the world to use, and for being such a patient maintainer with people in the issue queue (like myself). Kudos!!!

**Comment by facelessuser** [comment]
I'm glad you got it working!  That's why I push so hard to know **exactly** what people are doing. It actually saves me time as I can often can pick up on what they are doing wrong. Details that a user think are insignificant can some times be quite significant. If you are having issues, the best thing is to be as descriptive as possible. To much info is often better than too little.

I also wouldn't worry about "bothering" me with issues either. I'm pretty good at telling people what I do and don't have time for, or telling them to read the documentation if it is already there :smile:.

> The documentation in https://facelessuser.github.io/Rummage/installation could use some updating, and perhaps I can help with it

Certainly! I'll be the first to admit I'm not always the best at documenting. I try, but sometimes I don't describe things the best. Also, I often can forget to update certain areas.

> So the current documentation refers to a method to get Rummage installed with python 2.x

Personally, I would replace anything referencing Python 2 with Python 3. Come 2020 when Python 2 hits EOL, I will remove Python 2 support entirely.

We can definitely update `brew` information if you think it will be helpful.

> Finally run rummage: `python3 -m rummage`

I usually shy away from encouraging people to run rummage this way, only because when you do, Python can load local libraries. For instance, I often test rummage by navigating to the project folder and running `python3 -m rummage`. By doing this, it loads the local source. Luckily, I make sure Rummage is using relative imports (relative to the main module) and some other things to make sure it doesn't load stray Python  libraries when it doesn't find the `rummage` folder locally. But as I mention, if you are in a folder with a Python library called `rummage`, it will try to load that first. So 99% of the time `python3 -m rummage` is probably safe just due to the way I coded it internally, but there is a 1% chance you can load something you don't expect to.  I guess the same could be said for `python3 -m pip` vs `pip3`.

By running `rummage` from the command line (or `rummage3.7` for rummage in Python 3.7), it will not load local stuff on accident. This is the preferred way for most users. Just an FYI.

> You will see this error in your terminal while the Rummage window is open:

Yeah, you can ignore the `term_notify` error. I really should try and suppress that one of these days. It is handled gracefully as it just disables notifications for when the search is complete if `growl` or `terminal-notifier` is not installed, but it catches the issue with that assert and logs it to the console.
